title: Constance Crozier
logo: /images/headshot_border-min.png
description: Researcher working on simulation and control of future power systems. Most interested in integration of demand flexibility.
google_analytics: G-0MHBYB69TE
theme: jekyll-theme-minimal