title: Constance Crozier
logo: /images/headshot_border-min.png
description: Researcher working on simulation and control of future power systems. Currently most interested in unlocking demand flexibility to aid decarbonization.
google_analytics: G-0MHBYB69TE
theme: jekyll-theme-minimal