title:               Constance Crozier
url:                 https://constancecrozier.github.io
baseurl:             ""
google_analytics: G-0MHBYB69TE

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Constance Crozier
  url:               constancecrozier.github.io
  email:             ccrozier8@gatech.edu

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist